final List<Map<String, String>> bankList = [
  {"name": "AU Small Finance Bank", "logo": "assets/icon/bank/aubl.svg"},
  {"name": "Bank of Baroda", "logo": "assets/icon/bank/barb.svg"},
  {"name": "Bandhan Bank", "logo": "assets/icon/bank/bdbl.svg"},
  {"name": "Bank of India", "logo": "assets/icon/bank/bkid.svg"},
  {"name": "Central Bank of India", "logo": "assets/icon/bank/cbin.svg"},
  {"name": "City Union Bank", "logo": "assets/icon/bank/ciub.svg"},
  {"name": "Canara Bank", "logo": "assets/icon/bank/cnrb.svg"},
  {"name": "CSB Bank", "logo": "assets/icon/bank/csbk.svg"},
  {"name": "DCB Bank", "logo": "assets/icon/bank/dcbl.svg"},
  {"name": "Dhanlaxmi Bank", "logo": "assets/icon/bank/dlxb.svg"},
  {"name": "Federal Bank", "logo": "assets/icon/bank/fdrl.svg"},
  {"name": "HDFC Bank", "logo": "assets/icon/bank/hdfc.svg"},
  {"name": "ICICI Bank", "logo": "assets/icon/bank/icici.svg"},
  {"name": "IDBI Bank", "logo": "assets/icon/bank/idbi.svg"},
  {"name": "IDFC FIRST Bank", "logo": "assets/icon/bank/idfc.svg"},
  {"name": "India Post Payments Bank", "logo": "assets/icon/bank/idkl.svg"}, // Confirm `idkl` usage!
  {"name": "Indian Bank", "logo": "assets/icon/bank/indb.svg"},
  {"name": "Indian Overseas Bank", "logo": "assets/icon/bank/iodb.svg"},
  {"name": "Jammu & Kashmir Bank", "logo": "assets/icon/bank/jaka.svg"},
  {"name": "Karnataka Bank", "logo": "assets/icon/bank/karb.svg"},
  {"name": "Kotak Mahindra Bank", "logo": "assets/icon/bank/kkbk.svg"},
  {"name": "Karur Vysya Bank", "logo": "assets/icon/bank/kvbl.svg"},
  {"name": "Bank of Maharashtra", "logo": "assets/icon/bank/mahb.svg"},
  {"name": "Nainital Bank", "logo": "assets/icon/bank/ntbl.svg"},
  {"name": "Punjab & Sind Bank", "logo": "assets/icon/bank/psib.svg"},
  {"name": "Punjab National Bank", "logo": "assets/icon/bank/punb.svg"},
  {"name": "RBL Bank", "logo": "assets/icon/bank/ratn.svg"},
  {"name": "State Bank of India", "logo": "assets/icon/bank/sbin.svg"},
  {"name": "South Indian Bank", "logo": "assets/icon/bank/sibl.svg"},
  {"name": "Tamilnad Mercantile Bank", "logo": "assets/icon/bank/tmbl.svg"},
  {"name": "Union Bank of India", "logo": "assets/icon/bank/ubin.svg"},
  {"name": "UCO Bank", "logo": "assets/icon/bank/ucba.svg"},
  {"name": "Utkarsh Small Finance Bank", "logo": "assets/icon/bank/uitb.svg"},
  {"name": "YES Bank", "logo": "assets/icon/bank/yesb.svg"},

  {"name": "Axis Bank", "logo": "assets/icon/bank/axis.svg"},
  {"name": "IndusInd Bank", "logo": "assets/icon/bank/induslnd.svg"},
  {"name": "Equitas Small Finance Bank", "logo": "assets/icon/bank/bank.svg"},
  {"name": "Ujjivan Small Finance Bank", "logo": "assets/icon/bank/bank.svg"},
  {"name": "Suryoday Small Finance Bank", "logo": "assets/icon/bank/bank.svg"},
  {"name": "ESAF Small Finance Bank", "logo": "assets/icon/bank/esaf.svg"},
  {"name": "Jana Small Finance Bank", "logo": "assets/icon/bank/bank.svg"},
  {"name": "Fincare Small Finance Bank", "logo": "assets/icon/bank/bank.svg"},
  {"name": "Airtel Payments Bank", "logo": "assets/icon/bank/airtel.svg"},
  {"name": "Paytm Payments Bank", "logo": "assets/icon/bank/paytm.svg"},
  {"name": "FINO Payments Bank", "logo": "assets/icon/bank/bank.svg"},
];
