List<Map<String, String>> categoryData = [
  {"name": "Bills", "image": "bill.png"},
  {"name": "House", "image": "house.png"},
  {"name": "Books", "image": "books.png"},
  {"name": "Restaurant", "image": "restaurant.png"},
  {"name": "Food", "image": "diet.png"},
  {"name": "Transport", "image": "bus.png"},
  {"name": "Children", "image": "children.png"},
  {"name": "Vehicle", "image": "sport-car.png"},
  {"name": "Pills", "image": "drugs.png"},
  {"name": "Traveling", "image": "traveling.png"},
  {"name": "Cafe", "image": "coffee-cup.png"},
  {"name": "Mortgage", "image": "discount.png"},
  {"name": "Education", "image": "education.png"},
  {"name": "Flight Ticket", "image": "flight.png"},
  {"name": "Pets", "image": "fox.png"},
  {"name": "Gift", "image": "gift.png"},
  {"name": "Hospital", "image": "hospital.png"},
  {"name": "Hotel", "image": "hotel.png"},
  {"name": "Insurance", "image": "insurance.png"},
  {"name": "Beauty", "image": "makeup.png"},
  {"name": "Cinema", "image": "popcorn.png"},
  {"name": "Electronics", "image": "smartphone.png"},
  {"name": "Entertainment", "image": "talent-hunt.png"},
  {"name": "Club", "image": "dance.png"},
  {"name": "Garden", "image": "wheelbarrow.png"},
  {"name": "Clothes", "image": "woman-clothes.png"},
  {"name": "Electronics", "image": "smartphone.png"},
  {"name": "Furniture", "image": "wooden-chair.png"}
];
